# Generated by Django 5.1.1 on 2024-11-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_favouriteitem_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteItem',
        ),
    ]
