# Generated by Django 4.2.16 on 2024-12-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='card_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='cvv',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='expiration',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='name_card',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
