# Generated by Django 4.2.16 on 2024-12-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_shippingaddress_card_number_shippingaddress_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='payment_method',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
