# Generated by Django 4.2.16 on 2024-12-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_shippingaddress_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
