# Generated by Django 4.2.16 on 2024-12-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='appearance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
