# Generated by Django 4.2.16 on 2024-12-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_contact_us_customer_contact_us_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='order',
        ),
    ]
