# Generated by Django 4.2.16 on 2024-12-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_contact_us_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='messasge',
            new_name='messasge_info',
        ),
    ]
